version: '3.4'

services:
  message-broker:
    image: rabbitmq:alpine
    networks:
      - private
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_DATABASES=spaces
      - MONGO_SPACES_USER=${SPACE_MONGO_USER}
      - MONGO_SPACES_PASSWORD=${SPACE_MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
      - ./docker/mongo/init:/docker-entrypoint-initdb.d
    networks:
      - private
    ports:
      - 27019:27017
  client-portal-web:
    image: klassroom/client-portal-web
    build:
      context: .
      dockerfile: ./apps/client/portal/web/Dockerfile
    environment:
      NODE_ENV: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - public
    labels:
      - traefik.enable=true
      - traefik.http.routers.klassroomclientportalweb.rule=Host(`klassroom.docker.localhost`)
  api-gateway:
    image: klassroom/api-gateway
    build:
      context: .
      dockerfile: ./apps/api/gateway/Dockerfile
    depends_on:
      - server-spaces
      - server-courses
    environment:
      - NODE_ENV=development
      - WAIT_HOSTS=server-spaces:3000,server-courses:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - public
      - private
    labels:
      - traefik.enable=true
      - traefik.http.routers.klassroomapigateway.rule=Host(`klassroom.docker.localhost`) && PathPrefix(`/api`)
    command: sh -c "/wait && yarn nx serve api-gateway"
  server-spaces:
    image: klassroom/server-space
    build:
      context: .
      dockerfile: ./apps/server/space/Dockerfile
    depends_on:
      - mongo
      - message-broker
    environment:
      NODE_ENV: development
      MONGO_URL: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongo:27017/spaces?authSource=admin
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - private
  server-courses:
    image: klassroom/server-course
    build:
      context: .
      dockerfile: ./apps/server/course/Dockerfile
    depends_on:
      - mongo
      - message-broker
    environment:
      NODE_ENV: development
      MONGO_URL: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongo:27017/courses?authSource=admin
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - private

volumes:
  mongo_data:

networks:
  public:
    name: traefik_webgateway
    external: true
  private:
